---
title: "TempStats_Using_Chemical_Data_Times"
output:
  pdf_document: default
  html_notebook: default
---
Using the custom function TempStats, in the custom library PescStats, to get a bar plot and summary statistics of temperature data from a 10 minute interval near the end of chemical measurements. TempStats relies on functions from the package lubridate.

```{r libaries and functions}
#install.packages("lubridate")
library(lubridate)
library(devtools)
install_github("sbeaulieu/Pescadero/PescStats")
library(PescStats)

sum_stats_values<-function(x){
  decimal<-strsplit(as.character(x),"\\.")[[1]][2]
  if(is.na(decimal))
    digits <- 1
  else
    digits<-nchar(decimal)+1
  mean<-round(mean(x, na.rm=T), digits=digits)
  med<-round(median(x, na.rm=T), digits=digits)
  range<-round(max(x, na.rm=T)-min(x, na.rm=T), digits=digits)
  var<-round(var(x, na.rm=T), digits=digits)
  sd<-round(sd(x, na.rm=T), digits=digits)
  SEM<-round(SEM(x),digits=digits)
ISS_summary<-c(mean,med,range,var,sd,SEM)
}

TempStats_times<-function(x,t,d){
  ISS<-read.csv(x) #x is actual temperature log
  ISS$time<-ymd_hms(ISS$time)
  start<-ymd_hms(t) #t is the desired start time for temperature
  end<-ymd_hms(start)+minutes(d) #d is the durration of the measurement
ISS_duration<<-subset(ISS, time>start & time<end)
  start2<-paste(start)
  end2<-paste(end)
t_timeframe<-c(start2,end2)
}

chem_measure<-function(x,y,z){ #catered to pulling chem data times from various versions of the same spreadsheet
  all_ISS<-read.csv(x) #x is file name of this iteration of the sheet
  this_ISS<-subset(all_ISS, all_ISS$Station==y) #y is station number (00#)
  this_locale<-subset(this_ISS,this_ISS$location==z) #z is location (bullseye, away, excavated_bullseye)
  start2<-as.character(this_locale$Chem_Data_Start)
  end2<-as.character(this_locale$Chem_Data_End)
chem_time<-c(start2,end2)
}

ISS_Stats<-function(c,t,s){ #x is variable for whole ISS, c is variable for chemistry times, t is variable for temp times, s is for sum_stats
  x<-paste(t)
  y<-paste(c)
  x<-c(y,x,s)
}
```

ISS 001
```{r 001}
#Bullseye
TempStats("temp_log_001.csv","17-10-31 T15:05:00Z",10,"ISS1 Bullseye")
  t_timeframe<-TempStats_times("temp_log_001.csv","17-10-31 T15:05:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",001,"bullseye")
ISS1_bullseye<-ISS_Stats(chem_time,t_timeframe,ISS_summary)

#50cm Away
TempStats("temp_log_001.csv","17-10-31 T16:10:00Z",10,"ISS1 0.50m Away from Bullseye")
  t_timeframe<-TempStats_times("temp_log_001.csv","17-10-31 T16:10:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",001,"away")
ISS1_away<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
```
ISS 002
```{r 002}
#Bullseye
TempStats("temp_log_002.csv","17-10-31 T21:17:00Z",10,"ISS2 Bullseye")
  t_timeframe<-TempStats_times("temp_log_002.csv","17-10-31 T21:17:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",002,"bullseye")
ISS2_bullseye<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
#50cm Away
TempStats("temp_log_002.csv","17-10-31 T21:50:00Z",10,"ISS2 0.50m Away from Bullseye")
  t_timeframe<-TempStats_times("temp_log_002.csv","17-10-31 T21:50:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",002,"away")
ISS2_away<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
```
ISS 003
```{r 003}
#Bullseye
TempStats("temp_log_003.csv","17-11-01 T22:25:00Z",10,"ISS3 Bullseye")
  t_timeframe<-TempStats_times("temp_log_003.csv","17-11-01 T22:25:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",003,"bullseye")
ISS3_bullseye<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
#50cm Away
TempStats("temp_log_003.csv","17-11-01 T22:45:00Z",7, "ISS3 0.50m Away from Bullseye") #off bullseye 7min, not 10
  t_timeframe<-TempStats_times("temp_log_003.csv","17-11-01 T22:45:00Z",7)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",003,"away")
ISS3_away<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
```
ISS 004
```{r 004}
#Bullseye
TempStats("temp_log_004.csv","17-11-02 T02:15:00Z",10, "ISS4 Bullseye")
  t_timeframe<-TempStats_times("temp_log_004.csv","17-11-02 T02:15:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",004,"bullseye")
ISS4_bullseye<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
#50cm Away
TempStats("temp_log_004.csv","17-11-02 T04:15:00Z",10, "ISS4 0.50m Away from Bullseye")
  t_timeframe<-TempStats_times("temp_log_004.csv","17-11-02 T04:15:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",004,"away")
ISS4_away<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
#Bullseye Post Excavation
TempStats("temp_log_004.csv","17-11-02 T06:10:00Z",10, "ISS4 Excavated Bullseye")
  t_timeframe<-TempStats_times("temp_log_004.csv","17-11-02 T06:10:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",004,"excavated_bullseye")
ISS4_bull_excavated<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
```
ISS 005
```{r 005}
#Excavated? Bullseye
TempStats("temp_log_005.csv","17-11-03 T14:45:00Z",10, "ISS5 Bullseye")
  t_timeframe<-TempStats_times("temp_log_005.csv","17-11-03 T14:45:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",005,"bullseye")
ISS5_bullseye<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
#50cm Away
##no chem/temp data?? ->removed from Pescadero_20180621_Scotts_Times_TempData_sheet2.csv
#75cm Away
TempStats("temp_log_005.csv","17-11-03 T16:45:00Z",10, "ISS5 0.75m Away from Bullseye")
  t_timeframe<-TempStats_times("temp_log_005.csv","17-11-03 T16:45:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",005,"away")
ISS5_0.75m_away<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
```
ISS 006
```{r 006}
#Bullseye
TempStats("temp_log_006.csv","17-11-03 T18:22:00Z",3, "ISS6 Bullseye") #only 3min of chem/temp?
  t_timeframe<-TempStats_times("temp_log_006.csv","17-11-03 T18:22:00Z",3)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",006,"bullseye")
ISS6_bullseye<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
#Excavated Bullseye
TempStats("temp_log_006.csv","17-11-03 T22:35:00Z",10, "ISS6 Excavated Bullseye")
  t_timeframe<-TempStats_times("temp_log_006.csv","17-11-03 T22:35:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",006,"excavated_bullseye")
ISS6_bull_excavated<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
```
ISS 007
```{r 007}
#Excavated? Bullseye
TempStats("temp_log_007.csv","17-11-05 T06:25:00Z",10, "ISS Bullseye")
  t_timeframe<-TempStats_times("temp_log_007.csv","17-11-05 T06:25:00Z",10)
  ISS_summary<-sum_stats_values(ISS_duration$temperature)
  chem_time<-chem_measure("Pescadero_20180621_Scotts_Times_TempData_sheet2.csv",007,"bullseye")
ISS7_bullseye<-ISS_Stats(chem_time,t_timeframe,ISS_summary)
#50cm Away
##no away chem/temp data
```

Table of Times and Data
```{r}
all<-rbind(ISS1_bullseye,ISS1_away,ISS2_bullseye,ISS2_away,ISS3_bullseye,ISS3_away,ISS4_bullseye,ISS4_away,ISS4_bull_excavated,ISS5_bullseye,ISS5_0.75m_away,ISS6_bullseye,ISS6_bull_excavated,ISS7_bullseye)
columns<-c("Chem Start","Chem End","Temp Start","Temp End","Mean","Median","Range","Variance","St. Dev.","St. Err. Mean")
colnames(all)<-columns

print(all)
print("Temperature data times from near last 10min of chemistry data. All times are UTC, and temperatures in degrees C.")

```
